# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: user1234
      POSTGRES_USER: postgres_user
    ports:
      - 5432:5432
    volumes:
      - pgdata0:/data/db
    
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata0:
    driver: local