"""user_id in Meet add index

Revision ID: b0f57422bf61
Revises: daa3c5b5d209
Create Date: 2023-06-03 18:48:37.552482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f57422bf61'
down_revision = 'daa3c5b5d209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meets_user_id'), 'meets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meets_user_id'), table_name='meets')
    # ### end Alembic commands ###
