"""meet - user relationsship create

Revision ID: daa3c5b5d209
Revises: 96e02175efcc
Create Date: 2023-06-03 18:46:36.923379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa3c5b5d209'
down_revision = '96e02175efcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meets', type_='foreignkey')
    op.drop_column('meets', 'user_id')
    # ### end Alembic commands ###
