"""object meet model

Revision ID: e1023b7f2a6a
Revises: 9c7c3a424fc2
Create Date: 2023-06-02 21:35:04.969683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1023b7f2a6a'
down_revision = '9c7c3a424fc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
